export const CustomerDataFormat = {
  ID: 'customerId',
  编码: 'customerCode',
  名称: 'name',
  简称: 'shortName',
  等级: 'customerLevelValue',
  纳税规模: 'taxScale_value',
  欠款额度: 'creditLimit',
  客户分类: 'customerTypeValue',
  所属总公司: 'headquarters',
  所属地区: 'area',
  业务区域: 'bizArea',
  客户网站: 'website',
  法人代表: 'corporate',
  法人电话: 'corporatePhone',
  财务信息联系人: 'contactsFinancial',
  财务信息联系电话: 'phoneFinancial',
  开票信息单位名称: 'unitInvoice',
  开票信息开户行: 'bankInvoice',
  开票信息行号: 'bankidInvoice',
  开票信息税号: 'taxInvoice',
  开票信息联系电话: 'phoneInvoice',
  开票信息账号: 'accountInvoice',
  开票地址: 'addressInvoice',
  办款资料单位名称: 'unitPayment',
  办款资料开户行: 'bankPayment',
  办款资料行号: 'bankidPayment',
  办款资料账号: 'accountPayment',
  收件信息地址: 'accountReceipt',
  收件信息邮箱: 'postcodeReceipt',
  收件信息收件人: 'addressReceipt',
  收件信息联系电话: 'phoneReceipt',
  收件信息传真: 'faxReceipt',
  附件: 'attachment',
  备注: 'remark',
  是否启用: 'isEnabled',
  创建人: 'createBy',
  创建时间: 'createTime',
  修改人: 'updateBy',
  修改时间: 'updateTime',
  时间戳: 'modifiedDate'
}

export interface CustomerFormat{
    customerId:number,
    customerCode:string,
    name:string,
    shortName:string,
    customerLevelValue:string,
    taxScale_value:string,
    creditLimit:number,
    customerTypeValue:string,
    headquarters:string,
    area:string,
    bizArea:string,
    website:string,
    corporate:string,
    corporatePhone:string,
    contactsFinancial:string,
    phoneFinancial:string,
    unitInvoice:string,
    bankInvoice:string,
    bankidInvoice:string,
    taxInvoice:string,
    phoneInvoice:string,
    accountInvoice:string,
    addressInvoice:string,
    unitPayment:string,
    bankPayment:string,
    bankidPayment:string,
    accountPayment:string,
    accountReceipt:string,
    postcodeReceipt:string,
    addressReceipt:string,
    phoneReceipt:string,
    faxReceipt:string,
    attachment:string,
    remark:string,
    isEnabled:number,
    createBy:string,
    createTime:string,
    updateBy:string,
    updateTime:string,
    modifiedDate:string
}
// {
//   customerId:0,
//   customerCode:'',
// name:'',
// shortName:'',
// customerLevelValue:'',
// taxScale_value:'',
// creditLimit:0,
// customerTypeValue:'',
// headquarters:'',
// bizArea:'',
// website:'',
// corporate:'',
// corporatePhone:'',
// contactsFinancial:'',
// phoneFinancial:'',
// unitInvoice:'',
// bankInvoice:'',
// bankidInvoice:'',
// taxInvoice:'',
// phoneInvoice:'',
// accountInvoice:'',
// addressInvoice:'',
// unitPayment:'',
// bankPayment:'',
// bankidPayment:'',
// accountPayment:'',
// accountReceipt:'',
// postcodeReceipt:'',
// addressReceipt:'',
// phoneReceipt:'',
// faxReceipt:'',
// attachment:'',
// remark:'',
// isEnabled:'',
// createBy:'',
// createTime:'',
// updateBy:'',
// updateTime:'',
// modifiedDate:''
// }
